const ActionTypes = {
  GET_RANDOM: 'GET_RANDOM',
  GET_RANDOM_RESPONSE: 'GET_RANDOM_RESPONSE',
  FIND_ITEMS: 'FIND_ITEMS',
  FIND_ITEMS_RESPONSE: 'FIND_ITEMS_RESPONSE',
};

export default ActionTypes;
