const ActionTypes = {
  ADD_QUANTITY: 'ADD_QUANTITY',
  ADD_TO_CART_RESPONSE: 'ADD_TO_CART_RESPONSE',
  PREPARE_ORDER: 'PREPARE_ORDER',
  PREPARE_ORDER_RESPONSE: 'PREPARE_ORDER_RESPONSE',
};

export default ActionTypes;
