"use strict";

/* eslint-disable*/
module.exports = {
  registrarInterface:
  [{"constant":false,"inputs":[{"name":"referenceHash","type":"bytes32"}],"name":"submitOrderAndMakeDeposit","outputs":[],"payable":true,"type":"function"},{"constant":true,"inputs":[{"name":"index","type":"uint256"}],"name":"state","outputs":[{"name":"","type":"uint8"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"index","type":"uint256"}],"name":"newDeposit","outputs":[],"payable":true,"type":"function"},{"constant":true,"inputs":[],"name":"getOrderCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"orders","outputs":[{"name":"createdAt","type":"uint256"},{"name":"amount","type":"uint256"},{"name":"referenceHash","type":"bytes32"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"registrarStartDate","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"index","type":"uint256"}],"name":"getOrder","outputs":[{"name":"","type":"uint8"},{"name":"","type":"uint256"},{"name":"","type":"address[]"},{"name":"","type":"uint256"},{"name":"","type":"bytes32"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"uint256"}],"name":"deposits","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"node","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"fee","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"referenceHash","type":"bytes32"}],"name":"createOrder","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[],"payable":false,"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"index","type":"uint256"},{"indexed":true,"name":"referenceHash","type":"bytes32"}],"name":"OrderCreated","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"index","type":"uint256"},{"indexed":true,"name":"account","type":"address"},{"indexed":false,"name":"amount","type":"uint256"}],"name":"NewDeposit","type":"event"}]
  ,
  depositInterface:
  []
};
